name: Job Yaml  Pipeline
trigger: none
pool: Daisy Game Pool

jobs:
  - job: TerraformPlanning
    displayName: Terraform Planning
    pool: Daisy Game Pool
    steps:
    - task: TerraformTaskV4@4
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
        backendServiceArm: 'DoremonConnection'
        backendAzureRmResourceGroupName: 'pipeline'
        backendAzureRmStorageAccountName: 'pipelinestorage12account'
        backendAzureRmContainerName: 'doremon'
        backendAzureRmKey: 'dhondhu'
      


    - task: TerraformTaskV4@4
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
        environmentServiceNameAzureRM: 'DoremonConnection'

  - job: ManualValidiation
    displayName: Manual Validiation
    dependsOn: TerraformPlanning
    pool: server
    steps:
      - task: ManualValidation@1
        timeoutInMinutes: 1440
        inputs:
          notifyUsers: |
            Sanidhya1119@outlook.com
          instructions: 'Please validate the build configuration and resume'
          onTimeout: 'resume'

  - job: TerraformApply
    displayName: Terraform Apply
    dependsOn: ManualValidiation
    pool: Daisy Game Pool
    steps:
      - task: TerraformTaskV4@4
        displayName: Terraform Init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
          backendServiceArm: 'DoremonConnection'
          backendAzureRmResourceGroupName: 'pipeline'
          backendAzureRmStorageAccountName: 'pipelinestorage12account'
          backendAzureRmContainerName: 'doremon'
          backendAzureRmKey: 'dhondhu'
          
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
          environmentServiceNameAzureRM: 'DoremonConnection'