name: Yaml Pipeline
pool: Daisy Game Pool
trigger: none
steps:
  - task: TerraformTaskV4@4
    displayName: Terraform Init
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
      backendServiceArm: 'DoremonConnection'
      backendAzureRmResourceGroupName: 'pipeline'
      backendAzureRmStorageAccountName: 'pipelinestorage12account'
      backendAzureRmContainerName: 'doremon'
      backendAzureRmKey: 'dhondhu'
    

  - task: TerraformTaskV4@4
    displayName: Terraform Plan
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
      environmentServiceNameAzureRM: 'DoremonConnection'

  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
      environmentServiceNameAzureRM: 'DoremonConnection'