parameters:


stages:
  - stage: Implementation
    condition: eq(variables['Build.SourceBranchName'], 'main')
    displayName: Implementation
    jobs:
      - job: ManualValidiation
        displayName: Manual Validiation
        pool: server
        steps:
          - task: ManualValidation@1
            timeoutInMinutes: 1440
            inputs:
              notifyUsers: |
                Sanidhya1119@outlook.com
              instructions: 'Please validate the build configuration and resume'
              onTimeout: 'resume'

      - job: TerraformApply
        displayName: Terraform Apply
        dependsOn: ManualValidiation
        pool: Daisy Game Pool
        steps:
          - task: TerraformTaskV4@4
            displayName: Terraform Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
              backendServiceArm: '$(backendServiceArm)'
              backendAzureRmResourceGroupName: '$(backendAzureRmResourceGroupName)'
              backendAzureRmStorageAccountName: '$(backendAzureRmStorageAccountName)'
              backendAzureRmContainerName: '$(backendAzureRmContainerName)'
              backendAzureRmKey: '$(backendAzureRmKey)'
              
          - task: TerraformTaskV4@4
            displayName: Terraform Apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
              environmentServiceNameAzureRM: '$(parameters.backendServiceArm)'